# Generated by Django 2.2.9 on 2020-01-27 00:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_name', models.CharField(help_text='Map Name', max_length=64, verbose_name='map name')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Map',
            },
        ),
        migrations.CreateModel(
            name='Router',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.TextField(help_text='Point of Origin', verbose_name='source')),
                ('destiny', models.TextField(help_text='Point of Destiny', verbose_name='destiny')),
                ('distance', models.IntegerField(help_text='Distance in Kilometers', verbose_name='Distance')),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Map')),
            ],
            options={
                'verbose_name': 'Router',
            },
        ),
    ]
